version: "3.7"

services:
  AdminDEV:
      image: avosa/admin:dev
      build: .
      environment:
        - KEYPATH=${KEYPATH}
        - PUBLICKEY=${PUBLICKEY}
        - HOST=${HOST}
      depends_on:
        - RouterDEV
        - ThemeDEV
        - SecureDEV
        - ArtifactDEV
        - CommsDEV
        - VehicleDEV
      networks:
        - mango_net
      volumes: 
        - ../gate/certs:${KEYPATH}:ro
      ports:
        - "8088:8088"
      command: ["./wait-for-it.sh", "ThemeDEV:8093", "--", "python", "app.py"]

  RouterDEV:
    image: avosa/router:dev
    environment:
      - KEYPATH=${KEYPATH}
      - PUBLICKEY=${PUBLICKEY}
      - HOST=${HOST}
    volumes: 
      - ../gate/certs:${KEYPATH}:ro
    ports:
      - "8080:8080"
    networks:
        - mango_net

  FolioDEV:
    image: avosa/folio:dev
    environment:
      - KEYPATH=${KEYPATH}
      - PUBLICKEY=${PUBLICKEY}
      - HOST=${HOST}
    ports:
      - "8090:8090"
    networks:
      - mango_net
    volumes: 
      - ../folio/db:/db
      - ../gate/certs:${KEYPATH}:ro
    depends_on:
        - RouterDEV
    command: ["./wait-for-it.sh", "RouterDEV:8080", "--", "python", "app.py"]

  ThemeDEV:
    image: avosa/theme:dev
    environment:
      - KEYPATH=${KEYPATH}
      - PUBLICKEY=${PUBLICKEY}
      - HOST=${HOST}
    volumes: 
      - ../gate/certs:${KEYPATH}:ro
    ports:
      - "8093:8093"
    networks:
        - mango_net
    depends_on:
        - FolioDEV
    command: ["./wait-for-it.sh", "FolioDEV:8090", "--", "python", "app.py"]

  GateDEV:
    image: avosa/gate:dev
    environment:
      - KEYPATH=${KEYPATH}
      - PUBLICKEY=${PUBLICKEY}
      - PRIVATEKEY=${PRIVATEKEY}
      - HOST=${HOST}
    ports:
      - "80:80"
      - "443:443"
    networks:
      - mango_net
    depends_on:
      - AdminDEV
    volumes:
      - ../gate/certs:${KEYPATH}:ro
    command: ["./wait-for-it.sh", "AdminDEV:8088", "--", "python", "app.py"]

  AuthDEV:
    image: avosa/auth:dev
    environment:
      - KEYPATH=${KEYPATH}
      - PUBLICKEY=${PUBLICKEY}
      - HOST=${HOST}
    volumes: 
      - ../gate/certs:${KEYPATH}:ro
    ports:
      - "8094:8094"
    networks:
      - "mango_net"
    depends_on:
      - "ThemeDEV"
    command: ["./wait-for-it.sh", "ThemeDEV:8093", "--", "python", "app.py"]

  SecureDEV:
    image: avosa/secure:dev
    environment:
      - KEYPATH=${KEYPATH}
      - PUBLICKEY=${PUBLICKEY}
      - PRIVATEKEY=${PRIVATEKEY}
      - HOST=${HOST}
    ports:
      - "8086:8086"
    networks:
      - "mango_net"
    volumes:
      - ../secure/db:/db
      - ../gate/certs/:${KEYPATH}:ro
    depends_on:
      - "AuthDEV"
    command: ["./wait-for-it.sh", "AuthDEV:8094", "--", "python", "app.py"]

  ArtifactDEV:
    image: avosa/artifact:dev
    environment:
      - KEYPATH=${KEYPATH}
      - PUBLICKEY=${PUBLICKEY}
      - HOST=${HOST}
    ports:
      - "8082:8082"
    networks:
      - "mango_net"
    volumes: 
      - ../artifact/db:/db
      - ../gate/certs:${KEYPATH}:ro
    depends_on:
    - "RouterDEV"
    command: ["./wait-for-it.sh", "RouterDEV:8080", "--", "python", "app.py"]

  CommsDEV:
    image: avosa/comms:dev
    environment:
      - KEYPATH=${KEYPATH}
      - PUBLICKEY=${PUBLICKEY}
      - HOST=${HOST}
      - SMTPUsername=${SMTPUsername}
      - SMTPPassword=${SMTPPassword}
      - SMTPAddress=${SMTPAddress}
      - SMTPPort=${SMTPPort}
    ports:
      - "8085:8085"
    networks:
      - mango_net
    volumes: 
      - ../comms/db:/db
      - ../gate/certs:${KEYPATH}:ro
    depends_on:
        - RouterDEV
    command: ["./wait-for-it.sh", "RouterDEV:8080", "--", "python", "app.py"]
  
  VehicleDEV:
    image: avosa/vehicle:dev
    environment:
      - KEYPATH=${KEYPATH}
      - PUBLICKEY=${PUBLICKEY}
      - HOST=${HOST}
    ports:
      - "8098:8098"
    networks:
      - "mango_net"
    volumes: 
      - ../vehicle/db:/db
      - ../gate/certs:${KEYPATH}:ro
    depends_on:
    - "RouterDEV"
    command: ["./wait-for-it.sh", "RouterDEV:8080", "--", "python", "app.py"]

networks:
  mango_net:
    driver: bridge