name: Admin.APP
version: 1.0.0
description: Back-office application for mango services.
author: Louise van der Lith
repository: https://github.com/louisevanderlith/admin
environment:
  sdk: '>=2.0.0 <3.0.0'
dev_dependencies:
  build_runner: '>=1.6.2 <2.0.0'
  build_web_compilers:
dependencies:
  mango_ui: '^1.0.3'
  dart_toast: '^0.3.0'
  mango_stock: '^1.0.8'
  mango_vehicle: '^1.0.11'
  mango_wear: '^1.0.2'
  mango_artifact: '^1.0.2'
  mango_utility: '^1.0.5'
