name: Admin.APP
version: 0.1.10
description: Back-office application for mango services.
author: Louise van der Lith
repository: https://github.com/louisevanderlith/admin
environment:
  sdk: '>=2.1.0 < 3.0.0'
dev_dependencies:
  build_runner: '>=1.0.0 <2.0.0'
  build_web_compilers: '>=1.0.0 <2.0.0'
dependencies:
  mango_ui: '^1.0.3'
  dart_toast: '^0.3.0'
  mango_blog: '^1.0.0'
  mango_secure: '^1.0.1'
  mango_artifact: '^1.0.0'